version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGO: mongodb+srv://soumya-9641:soumya@cluster0.y7qxfvq.mongodb.net/CRUDOCKER?retryWrites=true&w=majority
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}